### ISSUE TITLE
CMAKE_MODULE_PATH Windows

### ISSUE THREAD

**Issue by thejustinwalsh** [chjj/node-cmk#1]
In the `prependModulePath(args)` function when running on windows the paths are not escaped and cmake is choking on the windows `\` path that is returned from `const MODULE_PATH = path.resolve(__dirname, '..', 'cmake');`.

By modifying the function with:
```js
  if (WINDOWS)
    paths = paths.replace(/\\/g, "/");

  out[1] = `CMAKE_MODULE_PATH=${paths}`;
```

CMake is able to handle the path and work properly.

I am not certain of the proper fix here as it appears that `__dirname` is working correctly on windows but CMake requires additional escaping or the use of the `/` to handle the string properly.

```
cmake version 3.18.2
node v12.18.3
```

**Comment by chjj** [comment]
Hmm, this is very strange. I wasn't encountering this issue on windows. CMake seemed to handle both `/` and `\\` just fine for me.

I will experiment with this some more to confirm, but we can probably add this fix regardless since it wouldn't hurt anything.

**Comment by thejustinwalsh** [comment]
Odd, maybe something else is happening here? What does your setup look like? No need to change, if we can not isolate the issue down to exactly why I get an error and you do not.

Is there a simple test project we can both confirm with?

I am currently helping a colleague test [ultralight-cra](https://github.com/igetgames/ultralight-cra) and I do not have any issues with the package on MacOS or Linux, just Windows.

```
PS C:\Users\theju\Projects\ultralight-cra-win> npm run prebuild

> ultralight-cra-win@0.1.0 prebuild C:\Users\theju\Projects\ultralight-cra-win
> cmake-node --root app configure

-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.27.29110.0
-- The CXX compiler identification is MSVC 19.27.29110.0
-- Detecting C compiler ABI info
CMake Error at C:/Users/theju/Projects/ultralight-cra-win/app/build/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (set):
  Syntax error in cmake code at
    C:/Users/theju/Projects/ultralight-cra-win/app/build/CMakeFiles/CMakeTmp/CMakeLists.txt:2

  when parsing string

    C:\Users\theju\Projects\ultralight-cra-win\node_modules\cmake-node\cmake

  Invalid character escape '\U'.


CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineCompilerABI.cmake:48 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:1 (project)
```
